addons:
  apt:
    packages:
      - git
      - make
      - curl

env:
  global:
    - TERRAFORM_VERSION=0.12.1

install:
  - make init

script:
  - make terraform/install
  - make terraform/get-plugins
  - make terraform/get-modules
  - make terraform/lint
  - make terraform/validate
