name: auto-release

on:
  push:
    branches:
      - release/v0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Get PR from merged commit to release branch
      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: get-merged-pull-request
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        with:
          # Do not auto-publish until release-drafter can publish a release
          # without making it the "latest" release.
          publish: false
          prerelease: false
          config-name: auto-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
